import { Product } from '../types/product';

export const mockProducts: Product[] = [
    {
      id: '1',
      name: 'Macbook Air 13 M1',
      productType: 'Laptop Mac',
      quantity: 10,
      price: 1799.99,
      SKU: 'ELEC-001',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '2',
      name: 'iPhone 13 Pro Max',
      productType: 'Smartphone iOS',
      quantity: 15,
      price: 1099.99,
      SKU: 'ELEC-002',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '3',
      name: 'iPad Pro 12.9 (2022)',
      productType: 'Tablet iOS',
      quantity: 8,
      price: 1099.99,
      SKU: 'ELEC-003',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '4',
      name: 'Apple Watch Series 7',
      productType: 'Smartwatch',
      quantity: 20,
      price: 399.99,
      SKU: 'ELEC-004',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '5',
      name: 'AirPods Pro',
      productType: 'Earbuds',
      quantity: 50,
      price: 249.99,
      SKU: 'ELEC-005',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '6',
      name: 'Apple TV 4K',
      productType: 'Streaming Device',
      quantity: 30,
      price: 179.99,
      SKU: 'ELEC-006',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '7',
      name: 'HomePod Mini',
      productType: 'Smart Speaker',
      quantity: 40,
      price: 99.99,
      SKU: 'ELEC-007',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '8',
      name: 'Magic Keyboard',
      productType: 'Keyboard',
      quantity: 25,
      price: 99.99,
      SKU: 'ELEC-008',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '9',
      name: 'Magic Mouse 2',
      productType: 'Mouse',
      quantity: 35,
      price: 79.99,
      SKU: 'ELEC-009',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '10',
      name: 'Macbook Pro 14 M1',
      productType: 'Laptop Mac',
      quantity: 12,
      price: 2499.99,
      SKU: 'ELEC-010',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '11',
      name: 'iMac 24" M1',
      productType: 'Desktop Mac',
      quantity: 7,
      price: 1299.99,
      SKU: 'ELEC-011',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '12',
      name: 'Mac Mini M1',
      productType: 'Desktop Mac',
      quantity: 15,
      price: 699.99,
      SKU: 'ELEC-012',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '13',
      name: 'iPad Mini 6',
      productType: 'Tablet iOS',
      quantity: 20,
      price: 499.99,
      SKU: 'ELEC-013',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    {
      id: '14',
      name: 'iPhone 12',
      productType: 'Smartphone iOS',
      quantity: 25,
      price: 699.99,
      SKU: 'ELEC-014',
      supplier: 'Apple',
      geoCoordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
]